apiVersion: v1
kind: Service
metadata:
  name: cloudeye-exporter
  namespace: default
  annotations:
    prometheus.io/port: '8087'
    prometheus.io/scrape: 'true'
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: cloudeye-exporter
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      name: metrics
  type: ClusterIP
  