apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudeye-exporter
  namespace: monitoring
  labels:
    app: cloudeye-exporter
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: "/metrics"
      scheme: "http"
      scrapeTimeout: 14s
      interval: 15s
      params:
        services:
          - SYS.ELB
      metricRelabelings:
        - sourceLabels: [namespace]
          regex: '(.*)'
          replacement: applications
          targetLabel: target_namespace
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: cloudeye-exporter
